version: '3.7'

services:
  app:
    container_name: adm_videos_app
#    image: jeisonborba/codeflix-catalog-admin:main-1
    build:
      context: ../../
      dockerfile: Dockerfile.dev
    restart: unless-stopped
    env_file:
      - .env.local
    ports:
      - 8080:8080
    networks:
      - adm_videos_network
      - adm_videos_services

networks:
  adm_videos_network:
  adm_videos_services:
    external: true