name: CI Pipeline

on:
  push:
    branches:
      - 'feature/**'
      - 'bugfix/**'
  # Enable manual trigger on Github Actions interface
  workflow_dispatch:

jobs:
  # Job to run the application tests
  tests:
    name: Tests runner
    runs-on: ubuntu-latest
    # Configure steps to run the job
    steps:
      # 1. Source code checkout
      - uses: actions/checkout@v3
      # 2. Configure JDk
      - name: Set up JDK@17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'adopt'
      # 3. Execute the application tests
      - name: Run application tests
        run: ./gradlew test